TRUNCATE CATEGORIES;
TRUNCATE MANUFACTURERS;
TRUNCATE PRODUCTS;

INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("CPU","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("Motherboard","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("GPU","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("RAM","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("Storage","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("PSU","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("Case","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("Cooler","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("OS","");
INSERT INTO CATEGORIES(NAME, DESCRIPTION) VALUES ("Peripheral","");

INSERT INTO MANUFACTURERS(NAME) VALUES ("AMD");
INSERT INTO MANUFACTURERS(NAME) VALUES ("ASUS");
INSERT INTO MANUFACTURERS(NAME) VALUES ("NVIDIA");
INSERT INTO MANUFACTURERS(NAME) VALUES ("Corsair");
INSERT INTO MANUFACTURERS(NAME) VALUES ("Samsung");
INSERT INTO MANUFACTURERS(NAME) VALUES ("Crucial");
INSERT INTO MANUFACTURERS(NAME) VALUES ("EVGA");
INSERT INTO MANUFACTURERS(NAME) VALUES ("NZXT");
INSERT INTO MANUFACTURERS(NAME) VALUES ("Noctua");
INSERT INTO MANUFACTURERS(NAME) VALUES ("Microsoft");

INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("AMD Ryzen 7 5800X 8-Core 16-Thread Processor", "", 299.99, 1, 1, 1, "https://c1.neweggimages.com/ProductImageCompressAll1280/19-113-665-V01.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("ASUS ROG Strix B550-F Gaming Motherboard", "", 199.99, 1, 2, 2, "https://c1.neweggimages.com/ProductImageCompressAll1280/14-137-632-03.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("NVIDIA GeForce RTX 3060 Graphics Card", "", 399.99, 1, 3, 3, "https://c1.neweggimages.com/ProductImageCompressAll1280/14-137-632-03.jpg",1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("Corsair Vengeance DDR5 32GB (2 x 16GB) 5200MHz RAM", "", 169.99, 1, 4, 4, "https://c1.neweggimages.com/ProductImageCompressAll1280/20-236-909-03.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("Samsung 970 EVO Plus 1TB NVMe M.2 SSD", "", 119.99, 1, 5, 5, "https://c1.neweggimages.com/ProductImageCompressAll1280/20-147-743-V01.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("Crucial MX500 1TB 3D NAND SATA SSD", "", 89.99, 1, 5, 6, "https://c1.neweggimages.com/ProductImageCompressAll1280/20-156-174-V09.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("EVGA SuperNOVA 750 G5 80 Plus Gold 750W Power Supply", "", 129.99, 1, 6, 7, "https://c1.neweggimages.com/ProductImageCompressAll1280/17-438-162-Z01.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("NZXT H510 Mid Tower ATX Case", "", 79.99, 1, 7, 8, "https://c1.neweggimages.com/ProductImageCompressAll1280/11-146-317-V01.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("Noctua NH-D15 Chromax Black Dual Tower CPU Cooler", "", 99.99, 1, 8, 9, "https://c1.neweggimages.com/ProductImageCompressAll1280/AYTVS230413152MJ7CD.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("Microsoft Windows 11 Home (Digital License)", "", 139.99, 1, 9, 10, "https://c1.neweggimages.com/ProductImageCompressAll1280/32-351-756-V01.jpg", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("ASUS TUF Gaming VG249Q 23.8” 144Hz Monitor", "", 199.99, 1, 10, 2, "https://c1.neweggimages.com/ProductImageCompressAll1280/0JC-001P-00JS8-07.png", 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID, MANUFACTURER_ID, IMAGE_URL, COST) VALUES ("Corsair K55 RGB Pro Keyboard & Harpoon RGB Mouse Combo", "", 69.99, 1, 10, 4, "https://assets.corsair.com/image/upload/c_pad,q_auto,h_1024,w_1024,f_auto/products/Bundles/CH-9226865-NA/-base-core-gaming-bundle-config-Gallery-K55-RGB-PRO-HARPOON-RGB-PRO-Bundle-01.webp?width=1080&quality=85&auto=webp&format=pjpg", 1);